### ISSUE TITLE
Hardigg Despawned

### ISSUE THREAD

**Issue by joed1989** [42MonthsAfter/Home#102]
Not a huge issue but had a Hardigg 2 that wouldn't place, dropped it and came back next day and it was gone.

**Comment by 42MonthsAfter** [comment]
Where were you trying to place it? If you couldn't place it, dropping it is just like tossing it into the world. It will despawn in its set lifetime.

**Comment by joed1989** [comment]
Yeah I know, the bug was more about the fact that it wouldn't place.

**Comment by 42MonthsAfter** [comment]
Where were you trying to place it?

**Comment by joed1989** [comment]
In my base, right next to two other ones. I tested the other ones and they
placed but that one just wouldn't

**Comment by joed1989** [comment]
I didn't know if that one might have come from a mod
