### ISSUE TITLE
Building Kits

### ISSUE THREAD

**Issue by joed1989** [42MonthsAfter/Home#106]
I thought at first someone was placing walls on top of the garages then I realized they are spawning in already in blueprint mode. Never saw this happen before.

**Comment by 42MonthsAfter** [comment]
You sure they are spawning in like that? I don't think that's possible. Wondering if one of the new guys placed a couple?

Can you give me more details like if you saw all of them like that or if it was at multiple locations on the map?

**Comment by joed1989** [comment]
Almost always on top of garages, check Portland, I dismantled a bunch but
if they are back then maybe that will help

**Comment by 42MonthsAfter** [comment]
Closing as redundant with this ticket: https://github.com/42MonthsAfter/Home/issues/109
