### ISSUE TITLE
Trader Items

### ISSUE THREAD

**Issue by joed1989** [42MonthsAfter/Home#107]
List of items not able to sell at trader
Hunter Backpack
Hunting Knife
Combat Knife
Sheath
Fishing Tackle Box
30rd Sporter 22 mag
Kitchen Knife
Fedora
Riflesling Black

**Comment by longlostblake** [comment]
NVG Headstrap
M1-9 (Mass weapon)
mini-14 (Mass Weapon)
Revolver
TACSAT Radio

**Comment by 42MonthsAfter** [comment]
- Hunter Backpack - `Can you get me a picture of this one? There are several and they all appear in the table @joed1989`
- ~Hunting Knife~ `Should be in the 10.0.0 update, weapon trader, melee and blade section`
- ~Combat Knife~ `Should be in the 10.0.0 update, weapon trader, melee and blade section`
- ~Sheath~ `Added leather and nylon to the trader, will be in 10.0.1 update`
- ~Fishing Tackle Box ~ `Added all Zeroy boxes to the trader, will be in 10.0.1 update`
- ~30rd Sporter 22 mag~ `Added along with the 15 round and the actual rifle itself, will be in 10.0.1 update`
- ~Kitchen Knife~  `Should be in the 10.0.0 update, weapon trader, melee and blade section`
- ~Fedora~ `Added all Mass Fedoras to the trader, will be in 10.0.1`
- ~Riflesling Black~ `Added all slings, rifle and melee, will be in hoster section after the 10.0.1`
- ~NVG Headstrap~ `Moved from the glasses section to be right under the NVGs in elecronics`
- ~M1-9 (Mass weapon)~ `Added all Mass M series rifles and mags, sound be in the 10.0.1 update`
- ~mini-14 (Mass Weapon)~ `Added with 10.0.1 update`
- ~Revolver~ `Added with 10.0.1 update`
- ~TACSAT Radio~ `Added with 10.0.1 update`
