### ISSUE TITLE
Land Claim Kit & Flagpole

### ISSUE THREAD

**Issue by longlostblake** [42MonthsAfter/Home#110]
I believe the Land claim kit is interferring with the built flagpole.

We've had a full locker dissapear and the tool cabinet get deleted which was almost full of tools and contained all our nails.

Issue started after placing down a land claim kit after building the initial flag pole. Now furniture placed down does not get the flag icon (to say its in your area/saved) so just gets deleted.

I've tried to remove the Land claim kit but all the tools were deleted. I resorted to shooting it to Ruined but i've no idea if that will help.

**Comment by 42MonthsAfter** [comment]
The claim kit allows you to turn the ability to build off and on. If you walk up to it once it is placed you will have an option to active and deactivate building. This is so other players can't build on your land.

If you have the land claim kit set to deactivate you won't be able to build yourself. You will need to set it to allowing building before you can continue to work on your flag. The flag has to be up for your gear to be protected. 

Sounds like you needed to turn off the claim kit and you could have finished the flag kit.

**Comment by longlostblake** [comment]
The claim kit was turned off while placing the locker, the tool bench was the first thing i ever placed down (The one you gave us at the start). And the flag was completed before the claim kit was even placed.

**Comment by 42MonthsAfter** [comment]
Completed, but was the flag up?

**Comment by longlostblake** [comment]
Im not so sure.

**Comment by longlostblake** [comment]
None of the furniture/lockers/storage we're putting down is saving at all.

We've placed down a further locker (and added junk to it) and its still dissapearing. 4 Containers removed now, total.

When we place the items down they dont appear to be getting the flag (like this: https://gyazo.com/bf838bb10c47be9823b1c1e22fa8f26e) so, you move away and they de-spawn.

I've no idea what's wrong, maybe its the flag pole thats broke but i dont know.

**Comment by RyLickliter** [comment]
Believe we have this resolved!! Will reopen if needed.
