### ISSUE TITLE
More Trader Items

### ISSUE THREAD

**Issue by SargeD** [42MonthsAfter/Home#111]
MVS Canteen - Black and I think others
MVS Warrior Helmet -Multicam Black
MVS Shroud - OD
S10 Respirator - Black and Tan
Lebedev_PL15 (handgun)

**Comment by longlostblake** [comment]
Assault Vest (WW2 Medical Version by mass)
MOLLE Tactical Rover Sling Pack 
Munghards Hiking Backpack (white varient)

**Comment by SargeD** [comment]
Large Molle Pouch - Black
Combat Backpack - Winter
MVS Raider pack - Multicam Tropic
Tactical Rucksack (Mass) - OD
Wolf AR-15
Holster (Mass) says PartisanM, don't know if thats the color its a green camo
MVS Canteen - OD
RMK-2 Respirator - Black
MVS Military Radio
M417
Molle US Assault Pack (Mass) Green/Brown Camo, same as the above holster
SP4K Ratnik Level 3 - Tan
MVS Radio Pack - Multicam Tropic
Munghards Hiking Backpack - Snow
Molle Tactical Rover Sling Back (Mass) same green/brown as above items
Assault Vest (Mass) - WW2 Smersh
5.56 Beta-C (100 Rd Drum)
Leupold 24x50 Scope
MVS High Cut Helmet - OD
Old Locker Green Kit
Flags
MRE's
Fronta Lemonade

**Comment by longlostblake** [comment]
Assault Vest (Mass' 'hip' varient)


5.56 Scout Magazine
5rd Pioneer Mag
9rd Deagle Mag
m300 Magazine

**Comment by RyLickliter** [comment]
## The following will be updated with 10.0.4 tonight at the 12:00 am EST restart:

~~MVS Canteen - Black and I think others~~
MVS Warrior Helmet -Multicam Black `All warrior helmets are in the trader price config, will have to explore further.`
~~MVS Shroud~~
~~S10 Respirator - Black and Tan~~
~~Lebedev_PL15 (handgun)~~
Assault Vest (WW2 Medical Version by mass) `Check in mass items, ticket` #114
~~MOLLE Tactical Rover Sling Pack~~
~~Munghards Hiking Backpack (white varient)~~
~~Large Molle Pouch - Black
~~Combat Backpack - Winter
~~MVS Raider pack - Multicam Tropic
~~Tactical Rucksack (Mass) - OD
Wolf AR-15 `Check in mass items, ticket` #114
~~Holster (Mass) says PartisanM, don't know if thats the color its a green camo  `Check in mass items, ticket` #114
~~MVS Canteen - OD~~
~~RMK-2 Respirator - Black~~
~~MVS Military Radio~~
M417 `Does this have a different name?`
Molle US Assault Pack (Mass) Green/Brown Camo, same as the above holster  `Check in mass items, ticket` #114
SP4K Ratnik Level 3 - Tan  `Check in mass items, ticket` #114
~~MVS Radio Pack - Multicam Tropic~~
~~Munghards Hiking Backpack - Snow~~
Molle Tactical Rover Sling Back (Mass) same green/brown as above items  `Check in mass items, ticket` #114
Assault Vest (Mass) - WW2 Smersh  `Check in mass items, ticket` #114
5.56 Beta-C (100 Rd Drum) `Which mod pack is this from?`
~~Leupold 24x50 Scope~~
MVS High Cut Helmet - OD `Is there another name for this?`
~~Old Locker Green Kit~~
~~Flags~~
MRE's  `Check in mass items, ticket` #114
Fronta Lemonade  `Check in mass items, ticket` #114
Assault Vest (Mass' 'hip' varient)  `Check in mass items, ticket` #114
M16A1 (Mass Vietnam version)  `Check in mass items, ticket` #114
PPSKN42 (Mass)  `Check in mass items, ticket` #114
~~5.56 Scout Magazine~~
5rd Pioneer Mag @longlostblake @SargeD `What one is this? I'm not finding it in the loot tables.`
~~9rd Deagle Mag~~
m300 Magazine  `Check in mass items, ticket` #114

**Comment by SargeD** [comment]
Completed
