### ISSUE TITLE
Loot Spawns

### ISSUE THREAD

**Issue by SargeD** [42MonthsAfter/Home#115]
I believe something is wrong with some of the loot types. Military loot seems to be spawning in the right areas but industrial and common have either been changed or removed with update 4.5. For example, The Garage Row Small Building,

![28](https://user-images.githubusercontent.com/36716178/130134247-070107b5-b7ee-43c8-9e9d-cc3d9e8361f1.jpg)

isn't spawning much loot and not the loot it use to. About 75% of the time there isn't any loot in them, it use to only be less than 25%. And this is where you would find items like Screwdrivers, Pliers, Lockpicks, Car Batteries, Truck Batteries, Vehicle Tires and Parts, Sharpening Stones, Duct Tape, Epoxy and sometimes building materials. I haven't found but maybe 1 of each of these items and they weren't in the garages. Common house loot like sewing kits and food aren't spawning in the rural houses like they would before. I haven't found a single sewing kit, and only about 2 leather sewing kits, both of these items were very common to find.

I think it needs to be looked into a bit and see if anyone else is experiencing the same issues.

**Comment by RyLickliter** [comment]
Believe I have this sorted out with the 10.5 update.
