### ISSUE TITLE
trader bug: car battery

### ISSUE THREAD

**Issue by Joshuabab** [42MonthsAfter/Home#116]
when selling the car battery at the quickstop trader it allows me to sell said battery for the charges instead of just the item itself. 50 charges per battery.

**Comment by longlostblake** [comment]
Likewise with any item that uses the "Bar" below the item such as duct tape/Sharpening Stone/Sewing kit/ etc...

**Comment by RyLickliter** [comment]
Should be fixed with all items that are containers in the sense of batteries, bandages, steaks, leather kits, etc.
