### ISSUE TITLE
High Risk Loot tables

### ISSUE THREAD

**Issue by longlostblake** [42MonthsAfter/Home#120]
The Risk to reward seems really off.

Secret Bunker:
We collected keycards for the bunker and did our run. We found a lot of (DAMAGED) MVS gear and a rifle safe but the entirety of the other loot was just Ammo and lots of vanilla WORN/(BADLY)DAMAGED weapons. It makes going out looking for the keycards completely pointless and just a waste of a few days. It was very underwhelming.

Area 42:
Area 42 is the biggest mess for a PVP zone. There is no reward here unless you want to collect NODS (We found ~12 pairs) Strangely, there seemed to be a lot of hunting boots and assault boots and i spotted a few vanilla magazines and vanilla weapons but nothing of any real value.

As two of the highest risk/difficult to get to areas its kind of ridiculous the amount of general loot we found. When in comparison, one trip to Paris Island (Which is relatively easy to access and sneak through) can net you two full vehicles full of loot, all pristine, with some of the rarer (gold) items which are worth a staggering amount.

It feels like the zones are flipped and it just doesn't make sense.

**Comment by RyLickliter** [comment]
Appreciate it! Will take a look at it. Haven't looked at the tier maps since the 4.5 map update.

**Comment by RyLickliter** [comment]
Updated the loot tables by putting the mod loot in the higher tiers areas only. Can only be found in specific sections of the main island. Should resolve. Let me know if you see any issues!
