### ISSUE TITLE
Vanilla Vehicles Despawning 

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/Home#121]
So, we have had 3 M3Ss and a Sarka despawn in our flag radius. Initially we thought it was the lack of keys or Carlocks, however, we just had a M3S despawn with a Carlock that had been in our base for a couple days. 
Interesting thing to note, we just brought back 2 Olgas and they both have flag markers on them, showing they are supposedly protected by the flag.

**Comment by RyLickliter** [comment]
Do you happen to know what colors they were? I think I found the issue with the M3S but curious about the Sarka.

**Comment by RyLickliter** [comment]
Fix should be going in right now!

Let me know if you want me to drop a couple replacements there to test with

**Comment by Raider2-1** [comment]
Yes please and thank you.
M3Ss

**Comment by RyLickliter** [comment]
dropped two off inside the gates
