### ISSUE TITLE
Codelock ownership 

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/Home#13]
Don't know if this is a bug or not but every time I leave the base and come back I get the promp to claim ownership on all our codelocks. Dident do that before

**Comment by 42MonthsAfter** [comment]
Getting back to old tickets, does this still seem to be an issue?

**Comment by MrWolfGaming** [comment]
Still happening but not as often now

**Comment by MrWolfGaming** [comment]
Mostly my gun rifels that do it now
