### ISSUE TITLE
Trader Names relating to MVS

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/Home#134]
![image](https://user-images.githubusercontent.com/83690102/133916734-350e4008-f22e-450a-ae99-ce79012e5d69.png)
![image](https://user-images.githubusercontent.com/83690102/133916736-d82becc3-7b6f-46d5-88c5-394fd49ff837.png)
![image](https://user-images.githubusercontent.com/83690102/133916738-78cc3a66-a283-40e4-a504-df734a84f1ee.png)
![image](https://user-images.githubusercontent.com/83690102/133916743-0236abed-0fbe-45f2-8c92-9e0799e25445.png)
![image](https://user-images.githubusercontent.com/83690102/133916745-4c43f27e-3e87-4f2f-9a00-a3e3e82562c6.png)
![image](https://user-images.githubusercontent.com/83690102/133916883-6b94fadf-6a3d-4a9f-972d-22b0b05bbf1b.png)
![image](https://user-images.githubusercontent.com/83690102/133916893-11e6e087-4c1c-4e5b-a098-5fef7027b01b.png)
![image](https://user-images.githubusercontent.com/83690102/133916897-8910f059-6f33-45cf-8bc3-6d15e2cbfe1c.png)
![image](https://user-images.githubusercontent.com/83690102/133916898-78dae3d2-6b8f-4100-9120-d2a01c954f06.png)
![image](https://user-images.githubusercontent.com/83690102/133916899-f0d83167-3c1b-4bbd-9ca4-3d57edc80dda.png)
![image](https://user-images.githubusercontent.com/83690102/133916905-ec69eefa-753d-49dc-810d-79a8e4de4aa9.png)
![image](https://user-images.githubusercontent.com/83690102/133916936-ecec39e8-7e39-4bc0-b2c0-58aa7c00edd1.png)
Tan Warrior Helmets can not be sold
![image](https://user-images.githubusercontent.com/83690102/133917037-f5d10f5e-9b05-49d4-bd72-b2689f407845.png)
ERDL, Multicam Black, Multicam, & Multicam tropic utility pouches are also missing from the traders
![image](https://user-images.githubusercontent.com/83690102/133917122-55135462-4ee0-4418-ad24-ef7e7d7e0e6c.png)
two tan rucksacks in the trader
Radio Packs ERDL, Multicam, Multicam Black and Multicam tropic are also missing.
Will update tomorrow, working on it with Sarge

**Comment by RyLickliter** [comment]
So you going to fix this or what?

**Comment by RyLickliter** [comment]
I updated / fixed all these...

**Comment by RyLickliter** [comment]
Will be included in the 10.1.0 update next Sunday!
