### ISSUE TITLE
Trader Issues

### ISSUE THREAD

**Issue by SargeD** [42MonthsAfter/Home#144]
Tool Trader:
Deer Photo listed twice
Gunwall Display Kit listed twice
Hardigg listed twice
No Hardigg2
Sleeping Bags listed twice
Head Torch listed twice
Head Torch, Flashlight and Construction light should be move to the Lights category
Black Cooler Box listed twice
Xmas lights are listed in multiple categories
The Camo nets from car cover mod need to be added to trader
Epoxy Putty listed in multiple categories
Wrench and Tire Iron listed in multiple categories

Food Trader:
Oranges and Bananas are priced 10x the other fruits and vegetables
Missing lunch meat, dog food and cat food
Missing Toxic cure
Medication sub category is empty
Skunk Items listed twice
Weed Buds are missing
Blue Candy is missing
CBD Relief Balm move to medicine
Remove the 25 dollar
Add 500 Euro

Clothes Trader:
Mass Items are all priced at $500
Missing Victorian Glasses
Missing White Cowboy Hat
Missing Top hat
Bandana Mask are all ready in the Hat Sub Category
Missing Hannabal and Jason mask
All plate carriers are listed twice
Zerroy fishing pants is listed incorrect
Multiple Ghillie Items listed twice
Tacticle and Utility belts are the same, maybe remove one from the loot list
Missing Rifleholsters
6B38 Bags listed incorrectly
Mass Sub category can be removed

Weapon Trader:
Holymakarel is listed incorrect
TWP M9A1 Bayonet listed incorrect
TWP Berretta92FS1 listed incorrect
Savage Stevens are shotguns, they are in the Rifle Sub category
Mini-14 should be listed under Rifles
Auto9 should be listed under handguns
TWP M24R is listed incorrect
TWP AG43 listed incorrect
TWP SteyrAug listed incorrect
TWP CalifasNomad listed incorrect
TWP AK5C listed incorrect
TWP AK5Green listed incorrect
TWP AK5CGrey listed incorrect
TWP PLR16 listed incorrect
TWP ScarLK listed incorrect
ScarLK mag listed under Assault Rifles
Missing Mcmillan Mag
Missing Rubber 12ga Bullets
Ammobox 12gaBB listed incorrect
SST30Orange and Halloween are listed under magazines
TWP M24R mag listed incorrectly
TWP AG43 mag listed incorrectly
TWP FNF2000 mag listed incorrectly
TWP AK5C mag listed incorrectly
TWP AK5CGreen mag listed incorrectly
TWP AK5CGrey mag listed incorrectly
TWP MK14 mag listed incorrectly
TWP PLR16 mag listed incorrectly
M4-A1 handguards listed twice
TWP M16A3 handle listed incorrectly
TWP Optic BlackDragon listed incorrectly
M16A4 handle listed twice
4 Suppressor listed incorrectly
MassSuppressor308 listed incorrectly
TWP LR300 Suppressor listed incorrectly
TWP Carabine Suppressor listed incorrectly
The sub category Bayonets is empty, move bayonets here
TWP Cosmetic Trashcan listed incorrectly

Auto Trader:
Humvee parts aren't in the trader
Batteries, spark plugs and radiators are listed under two different traders

**Comment by RyLickliter** [comment]
I might suggest breaking this into tickets for each section. We shouldn't be committing more than 20 or so updates per push to just be on the safe side of things.

**Comment by SargeD** [comment]
I'm going to close this and split it up by Trader
