### ISSUE TITLE
Air drops despawn on restart. 

### ISSUE THREAD

**Issue by R3DSTARMAN** [42MonthsAfter/Home#17]
Maybe they should stay like the zombies? I spent many rounds (min 120) killing zombies then the restart killed the drop/ loot.

**Comment by 42MonthsAfter** [comment]
Digging into it, it doesn't look like there is much I can do about this one outside try to tweak the timing of the drops so they don't initiate if there is less than 60 minutes before a scheduled restart. 

This won't fix is the issue if there is a crash, but it will get us closer.
