### ISSUE TITLE
Security Keycard and Bunker door malfuction.

### ISSUE THREAD

**Issue by Cassidy420** [42MonthsAfter/Home#175]
I used the security keycard to open the bunker door up in Mt. K. The siren went off but the doors never opened.

I clicked open the door, proof I used the keycard.

![20211028163741_1](https://user-images.githubusercontent.com/93274246/139340555-2ce00960-e805-4bd4-9bbe-b46d357468b6.jpg)

I waited up to three or four minutes before taking this screenshot of the door still not open.

![20211028164059_1](https://user-images.githubusercontent.com/93274246/139340581-6b178641-8f39-45a2-a3e3-c05d865d2997.jpg)

This is my first time going into the bunker but I was told the door should open almost, if not, immediately.

**Comment by RyLickliter** [comment]
Have reached out to the modder and the mod community to see if anyone else is having similar issues. If not, it will help me narrow down what is causing it.

**Comment by RyLickliter** [comment]
Interesting update... Testing against some of the new mods today...

![Screenshot 2021-10-30 150131](https://user-images.githubusercontent.com/8458331/139555490-21214f88-c667-4b28-862d-b3e58d2806b1.png)

**Comment by RyLickliter** [comment]
Getting closer...

![20211030155320_1](https://user-images.githubusercontent.com/8458331/139556748-c937bad3-eea6-4189-8a3f-560e3022e417.jpg)

**Comment by RyLickliter** [comment]
Think we got this fixed. Pushing a 10.1.2 update with this fix included. Check the #change-log for more info.
