### ISSUE TITLE
Update Pricing on Top Tier TWP Loot

### ISSUE THREAD

**Issue by RyLickliter** [42MonthsAfter/Home#178]
Since some of the TWP gear is now "super top tier" and only available in the high risk sections, we should adjust the prices so that those super items are at least 2x the value when sold.

**Comment by SargeD** [comment]
Where can I find the list of items that are "super top tier"? I'll work on that this week

**Comment by RyLickliter** [comment]
If you search only within the TWP section of the typs.xml for:

    <value name="Tier7" />
    <value name="Tier10" />
    <value name="Tier12" />
    <value name="Tier13" />
  </type>
  
  It's all the ones that show up, should apply to both mags and weapons themself.

**Comment by SargeD** [comment]
Pushed to github 11/10 2:05am
