### ISSUE TITLE
90% of my base disappeared.

### ISSUE THREAD

**Issue by Cassidy420** [42MonthsAfter/Home#179]
I haven't been on in over a week. I don't think anyone in my group has been but I highly doubt we have been raided because only odd things are missing. Like the barbed wired walls and 90% of our containers. I would like to provide screenshots but I'm not sure what a bunch of screenshots of empty spaces is going to do?

Edit: Our base is at the Warren Cove radio station up the hill. We had two T3 walls and three T1 walls with barbed wire attached to the holes in our base. We are also missing a safe with countless money, and military crates with tons of ammo and mags. As well as two gardening houses and just countless other items I cannot name.

**Comment by RyLickliter** [comment]
To confirm, no lockers? Just military creates? Do you happen to know what ones they were? We have multiple from different mods.

Do you know which greenhouse? There are a couple different models / kits. 

I will get you back everything you lost, just get me a list while I get this figured out.

**Comment by Cassidy420** [comment]
Sorry, its taken a couple days to compile this list.

I am unsure of the greenhouses mod but they were metal if that helps.
The military crates were Mungards, I believe. We had 4 military crates.
We had two Large Tents, they are green and military looking. I'm pretty sure they are vanilla.
We had many other small containers but the ones listed above and the T3 walls are the only real important things to us.
The rest, it just gives us a reason to go out adventuring more.

**Comment by RyLickliter** [comment]
Yeah, we covered this in chat, but you have to have a flag up or the items will be treated like anything on the ground with a lifetime of a couple hours opposed 45 days.

I set up a flag so you should be good for a while, just make sure it stays up. 

Happy to get you back anything you lost.
