### ISSUE TITLE
Heli Crash Loot Spawns

### ISSUE THREAD

**Issue by Raider2-1** [42MonthsAfter/Home#180]
I've noticed some weirdness when it comes to the things that are spawning at heli spawns. For one, incomplete vehicles keep spawning at them. I've also noticed animals and stationary zombies spawning at them. For example the most recent one I found, it had a cow, wolf, deer and a stationary zombie. It also had a Gunter 2.

**Comment by RyLickliter** [comment]
Sarge just pushed a fix for this.
