### ISSUE TITLE
Loot Drop

### ISSUE THREAD

**Issue by joed1989** [42MonthsAfter/Home#90]
I've noticed over the past couple weeks that the same items are dropping all over the map in the same type of locations, ie every time I went into a military Quonset hut (green domed barracks) the only gun that I kept finding in them was the PPSKN42. The only military clothing was all snow gear. When I went into houses I kept finding the Armsman shotgun. It just seems that instead of finding random items its cyclical and the same items spawn all over at the same time.

**Comment by 42MonthsAfter** [comment]
This is interesting... I've reset the stock loot table numbers and tweaked a couple other settings that I think might take care of it. Please let me know if you still see it!!!

**Comment by joed1989** [comment]
I did notice a difference the other night I was on, maybe it's fixed but I'll keep my eyes open
