### ISSUE TITLE
Cant sell anything at the trader.

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/Home#94]
for some reason i cant sell anything at the trader. i did try during the event day and i did think it was somthing with my game but then again today i cant sell anything

**Comment by 42MonthsAfter** [comment]
If you've seen all the updates to that mod in the last week, there is some crazyness going on. 

I found that entering and leaving the trader menus a couple times before I got started helped everything load. I have reported this to the mod creator so hope there is a fix asap.

**Comment by 42MonthsAfter** [comment]
Checking to see if you're still having this bug?

**Comment by MrWolfGaming** [comment]
Same with this one. Will go up to qs after work 😊

**Comment by MrWolfGaming** [comment]
dont have time to go up and check, Need to remove our gate, build a new one and run all the way up there. So need to test it at another time
