### ISSUE TITLE
Dead Zombies and no working bears/wolf packs

### ISSUE THREAD

**Issue by Telsana79** [42MonthsAfter/Home#96]
Hi, 

in the last 4 days I meet only dead zombies. Westbrooke, Mountainville, Waldoboro, Paris Island etc. all zombies are dead and free for loot.

Also I meet now 6 times dire wolfs or bears ... not one was moving correctly all stucked (without the ambulance car).

That's a little bit to easy. It looks like I am a moving safe zone.

Regards
Telsana

**Comment by Telsana79** [comment]
Bears around Mount Khatadin are working (killed 3 bears) but still the probs with the dead zombies... atm all zombies are free loot for me which would be to easy... I don't know if I have to kill myself ingame to solve that bug.

**Comment by 42MonthsAfter** [comment]
Are they dead when you find them?  If so, that's not how the safe zone works, the safe zone would remove them completely, not just kick.

You wouldn't be able to loot.

**Comment by Telsana79** [comment]
They are dead and I can loot them. And I checked now so many locations it can't be other players. I alos try to attracted zombies to my position by shoting in the air nothing was coming (and i did that in towns).

**Comment by Telsana79** [comment]
Are wolf packs active haven't hear or seen any and walked three times up and down deer isle (normally on other servers I had 1-3 packs at least, and one bear; on M42 only bears on the mountain all others where stucked)?

**Comment by 42MonthsAfter** [comment]
Sounds like these have been resolved!
