### ISSUE TITLE
Some stuff gone sens update

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/Home#97]
All the cars are gone

80% of our code lockes are gone but the stuff in them are still there
one gate door is gone. Main gate is till intact so no one raided us.

One Large tent is gone and beds are gone.

one in game door cant be opend to our basment.

Our normal flag is gone but the pole is still there.

**Comment by 42MonthsAfter** [comment]
Whoa... thats a lot of stuff. Have you checked since the mod updates have been rolling out? It appears to be fixing a lot of issues 1.13 left

**Comment by MrWolfGaming** [comment]
Will check it out after work 😊

**Comment by MrWolfGaming** [comment]
it is still gone + our flag pole is now gone to  :P
