### ISSUE TITLE
code on main gate is changed

### ISSUE THREAD

**Issue by MrWolfGaming** [42MonthsAfter/Home#98]
Notised not that we cant get out of our base cus the main gate have another code all the sudden

**Comment by 42MonthsAfter** [comment]
ahahaha NO!!!

Have you tried again since the update to the locks? Curious if this was resolved with the mod update or if it is an issue that will linger because of pre / post 1.13.  Either way let me know when you are on and I will let you out. ha

**Comment by MrWolfGaming** [comment]
I will try when I get home from work today.

**Comment by MrWolfGaming** [comment]
still lock inside our base :P
