### ISSUE TITLE
Car Key

### ISSUE THREAD

**Issue by joed1989** [42MonthsAfter/Home#99]
Beside the issues others have stated about code locks and cars, looks like my car didn't despawn but my key no longer works.

**Comment by 42MonthsAfter** [comment]
Have you tried again since the update to the locks? Curious if this was resolved with the mod update or if it is an issue that will linger because of pre / post 1.13.

**Comment by joed1989** [comment]
I actually dumped the truck, found a new one and moved everything over.
Sorry

**Comment by 42MonthsAfter** [comment]
No worries, closing out then!
